### ISSUE TITLE
[Doc] Создать wiki-страницу с требованиями к проекту

### ISSUE THREAD

**Issue by Gentser** [Gentser/Graph_Bridges#2]
Добавить нечто вроде ТЗ к нашему проекту.

**Comment by Desamod** [comment]
[https://github.com/Gentser/Graph_Bridges/wiki/%D0%A2%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BA-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D1%83.](url)

**Comment by Desamod** [comment]
https://github.com/Gentser/Graph_Bridges/wiki/%D0%A2%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BA-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D1%83

**Comment by Desamod** [comment]
https://github.com/Gentser/Graph_Bridges/wiki/Требования-к-проекту.

**Comment by Desamod** [comment]
https://github.com/Gentser/Graph_Bridges/wiki/%D0%A2%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BA-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D1%83.

**Comment by Desamod** [comment]
[https://github.com/Gentser/Graph_Bridges/wiki/%D0%A2%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BA-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D1%83.](url)

**Comment by Desamod** [comment]
https://github.com/Gentser/Graph_Bridges/wiki/%D0%A2%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BA-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D1%83.

**Comment by Desamod** [comment]
Для того, чтобы просмотреть данную страницу, скопируйте ссылку ниже в браузер:
https://github.com/Gentser/Graph_Bridges/wiki/Требования-к-проекту.

**Comment by Gentser** [comment]
https://github.com/Gentser/Graph_Bridges.wiki.git

**Comment by Gentser** [comment]
github.com/Gentser/Graph_Bridges.wiki.git
